---
# configuration tasks for teamspeak

- name: "Configuration : Create TeamSpeak 3 Server configuration file"
  template:
    src: ts3server.ini.j2 
    dest: "{{ ts3server_dir }}/{{ teamspeak_ini_filename }}"
    mode: 0644
    owner: "{{ teamspeak.user }}"
    group: "{{ teamspeak.user }}"
  notify:
    - Restart TeamSpeak 3 Server

- name: "grep ServerAdmin Password"
  shell: 'journalctl -u teamspeak3-server.service --since today | grep -oEi \'password= "(.*)"\' | cut -d\" -f2 | tail -n1'
  register: __ts3_serveradmin_password
