---
# configuration tasks for teamspeak
- name: Set TeamSpeak 3 Server directory fact
  set_fact:
    ts3server_dir: "{{ teamspeak.home }}/{{ teamspeak.symlink }}/teamspeak3-server_linux_amd64"

- name: Create TeamSpeak 3 Server configuration file
  template:
    src: ts3server.ini.j2 
    dest: "{{ ts3server_dir }}/{{ teamspeak_ini_filename }}"
    mode: 0644
    owner: "{{ teamspeak.user }}"
    group: "{{ teamspeak.user }}"
  notify:
    - Restart TeamSpeak 3 Server
