---
# handlers file for teamspeak

- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart TeamSpeak 3 Server
  service:
    name: teamspeak3-server
    state: restarted

- name: Prune older TeamSpeak 3 server versions
  shell: "find {{ teamspeak.home }}/teamspeak3-server_linux_amd64-*/ -maxdepth 1 -iname 'teamspeak3-server_linux_amd64' -type d | sort | head -n-{{ teamspeak.keep }} | xargs rm -rf"
